name = "sugardoorgate"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "sugardoorgate-db"
database_id = "84b1a342-6cf1-4516-b519-6cff71077bac"
